version: 2
updates:
- package-ecosystem: cargo
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-cargo)"
  groups:
    cargo-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
  directories:
  - '*'
- package-ecosystem: docker
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-docker)"
  groups:
    docker-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
  directories:
  - '*'
- package-ecosystem: github-actions
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: "chore(deps-github-actions)"
  groups:
    github-actions-non-major:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
  directory: /
