---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    DRONE_SSH_KEY:
      from_secret: drone_ssh_key
    PLUGIN_DEPTH: 5

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.4
  commands:
  - sed -i 's/USER app/USER root/g' ./Dockerfile
  - docker build -t prima/localauth0-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - git-clone

- name: build-artifact
  image: prima/localauth0-ci:${DRONE_COMMIT}
  commands:
  - cargo build
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - build-image

- name: build-web
  image: prima/localauth0-ci:${DRONE_COMMIT}
  commands:
  - trunk build web/index.html
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - build-image

- name: build-localauth0
  image: public.ecr.aws/prima/drone-tools:1.21.4
  commands:
  - ./build.sh . 'public.ecr.aws/prima/localauth0:'
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  when:
    event:
    - tag
    ref:
    - refs/tags/*
  depends_on:
  - build-image
  - build-artifact
  - build-web

- name: noop
  image: public.ecr.aws/prima/drone-tools:1.21.4
  commands:
  - echo "Nothing to do"
  when:
    event:
      exclude:
      - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

node:
  reserved: common

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

node:
  reserved: common

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default

---
kind: signature
hmac: 84173da6bce549f3f613d79c24416a92dbca5e2dddaad2f77f58a8f6bdad6c5c

...
