files:
  - path: Cargo.toml
    pattern: "\\[package\\][\\s\\S]*?version = \"{version}\""
  - path: README.md
    pattern: "image: public.ecr.aws/c6i9l4r6/localauth0:{version}"
  - path: README.md
    pattern: "docker run -d -p 3000:3000 public.ecr.aws/c6i9l4r6/localauth0:{version}"

