FROM clux/muslrust:stable as builder

# Installing trunk
RUN rustup target add wasm32-unknown-unknown && \
    cargo install --locked trunk

# Copying the project resources
COPY Cargo.lock .
COPY Cargo.toml .
COPY src ./src
COPY web ./web

RUN set -x && \
    # Building the binary and the web distro
    cargo build --target x86_64-unknown-linux-musl --release && \
    # Build web distro as release with trunk
    trunk build --release web/index.html

# Copying resources to build directory
RUN set -x &&  \
    mkdir -p /build/web/dist/ && \
    cp target/x86_64-unknown-linux-musl/release/localauth0 /build/ && \
    cp -r web/dist/ /build/web/

# Create the final minimal docker image
FROM scratch

ENV RUST_LOG="error,localauth0=info"
COPY --from=builder /build /

CMD ["/localauth0"]