FROM clux/muslrust:stable as builder

# Installing trunk
RUN rustup target add wasm32-unknown-unknown && \
    cargo install --locked trunk

# Copying the project resources
COPY Cargo.lock .
COPY Cargo.toml .
COPY src ./src
COPY web ./web

# Temp: copying pyxis
COPY pyxis ./pyxis

# Building the binary and the web distro
RUN set -x && cargo build --target x86_64-unknown-linux-musl --release

# Build web distro
RUN set -x && trunk build --release web/index.html

# Create build directories
RUN mkdir -p /build/web/dist/

# Copying resources to build directory
RUN set -x &&  \
    cp target/x86_64-unknown-linux-musl/release/localauth0 /build/ && \
    cp -r web/dist/ /build/web/

# Create the final minimal docker image
FROM scratch

ENV RUST_LOG="error,localauth0=info"
COPY --from=builder /build /

CMD ["/localauth0"]