FROM debian:10.2-slim

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install --no-install-recommends -y \
    libssl1.1 \
    libssl-dev && \
  rm -r /var/lib/apt/lists/* && \
  apt-get clean && \
  apt-get autoremove

COPY target/debug/localauth0 /localauth0
COPY web/dist /web/dist

ENTRYPOINT ["/localauth0"]
