[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["trunk-build"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.trunk-build]
command = "trunk"
args = ["build", "web/index.html"]
